# This must be the project id on cloud.google.com
application: hellocloud-1349
# The version here is what will be set to the default by update.bat and shown on appspot
version: 4
# The following three will be the same for all projects
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
  
libraries:
- name: webapp2
  version: "2.5.2"